version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  router01:
    image: cisshgo:latest
    container_name: router01
    command: go run cissh.go -listners 1
    ports:
      - 10000:10000
