---
- name: Prepare instance
  hosts: instance
  gather_facts: no

  tasks:
    - name: Save interface-data
      copy:
        src: data/interface-data.txt
        dest: /tmp/interface-data.txt

    - name: "Wait for Elasticsearch to come up"
      uri:
        url: "http://{{ elasticsearch_db | default('localhost') }}:9200/_cluster/health?wait_for_status=green&timeout=30s"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 1
